{% set data = load_setup_py_data() %}

package:
  name: publish-conda-stack
  version: {{ data['version'] }}

source:
  path: ..

build:
  noarch: python
  script:
        - python -m pip install --no-deps --ignore-installed .
        - mkdir -p $PREFIX/etc/conda/activate.d
        - echo 'eval "$(register-python-argcomplete publish-conda-stack -s bash)"' > $PREFIX/etc/conda/activate.d/activate_publish-conda-stack.sh
  entry_points:
    {% for ep in data['entry_points']['console_scripts'] %}
    - {{ ep }}
    {% endfor %}
requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    # dependencies are defined in setup.py
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  imports:
    - publish_conda_stack
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - pytest tests

about:
  home: https://github.com/ilastik/publish-conda-stack
  author: Stuart E. Berg, Carsten Haubold
  summary: Short description
